# Generated by Django 5.0.2 on 2024-02-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='category',
            new_name='wheel',
        ),
        migrations.AddField(
            model_name='detail',
            name='wheel_reference_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wheel',
            name='details',
            field=models.ManyToManyField(related_name='wheels', to='wheel.detail'),
        ),
    ]
