# Generated by Django 5.0.2 on 2024-02-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheelimages',
            name='image',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
    ]
