# Generated by Django 5.0.2 on 2024-03-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='sizes',
            field=models.ManyToManyField(blank=True, null=True, to='wheel.categorysizes'),
        ),
    ]
