# Generated by Django 5.0.2 on 2024-02-23 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0002_rename_category_detail_wheel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='detail',
            name='width',
            field=models.IntegerField(default=65),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wheels', to='wheel.category'),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='climate',
            field=models.IntegerField(choices=[(1, 'Летние'), (2, 'Зимние'), (3, 'Универсальный')]),
        ),
    ]
