# Generated by Django 5.0.2 on 2024-02-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0002_alter_detail_lenght_alter_detail_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheel',
            name='details',
            field=models.ManyToManyField(blank=True, related_name='wheels', to='wheel.detail'),
        ),
    ]
