# Generated by Django 5.0.2 on 2024-02-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0002_alter_wheelimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheel',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wheelimages',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
