# Generated by Django 5.0.2 on 2024-02-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0003_order_detail_width_alter_wheel_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='lenght',
            field=models.IntegerField(default=170),
        ),
    ]
