# Generated by Django 5.0.2 on 2024-03-01 10:26

import wheel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0003_alter_wheel_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='passport_image',
            field=models.FileField(blank=True, null=True, upload_to=wheel.models.order_image_path),
        ),
    ]
