# Generated by Django 5.0.2 on 2024-03-09 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0004_alter_order_passport_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='lenght',
        ),
        migrations.AddField(
            model_name='detail',
            name='length',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detail',
            name='price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='width',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wheels', to='wheel.category'),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='climate',
            field=models.IntegerField(blank=True, choices=[(1, 'Летние'), (2, 'Зимние'), (3, 'Универсальный')], null=True),
        ),
    ]
