# Generated by Django 5.0.2 on 2024-02-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0004_detail_lenght'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wheels',
            field=models.ManyToManyField(to='wheel.wheel'),
        ),
        migrations.AddField(
            model_name='wheel',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
