# Generated by Django 5.0.2 on 2024-02-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0005_wheel_images_alter_wheel_climate_alter_wheel_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wheel',
            name='category',
        ),
        migrations.AddField(
            model_name='wheel',
            name='category',
            field=models.ManyToManyField(to='wheel.category'),
        ),
    ]
