# Generated by Django 5.0.2 on 2024-03-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0005_remove_detail_lenght_detail_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='month_3_price',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='month_6_price',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detail',
            name='month_9_price',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
