# Generated by Django 5.0.2 on 2024-02-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0005_order_wheels_wheel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='wheels',
        ),
        migrations.AddField(
            model_name='order',
            name='details',
            field=models.ManyToManyField(blank=True, related_name='orders', to='wheel.detail'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='passport_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
