# Generated by Django 5.0.2 on 2024-03-10 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0006_detail_month_3_price_detail_month_6_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='wheel_reference_id',
        ),
    ]
