# Generated by Django 5.0.2 on 2024-02-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0006_remove_wheel_category_wheel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wheel',
            name='size',
        ),
        migrations.AddField(
            model_name='category',
            name='size',
            field=models.IntegerField(choices=[(13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], default=1),
            preserve_default=False,
        ),
    ]
