# Generated by Django 5.0.2 on 2024-02-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0007_remove_wheel_size_category_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')])),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='size',
        ),
        migrations.AddField(
            model_name='category',
            name='sizes',
            field=models.ManyToManyField(to='wheel.size'),
        ),
    ]
