# Generated by Django 5.0.2 on 2024-03-10 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0007_remove_detail_wheel_reference_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
