# Generated by Django 5.0.2 on 2024-03-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0008_remove_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheel',
            name='company',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
