# Generated by Django 5.0.2 on 2024-02-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0008_size_remove_category_size_category_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wheel',
            name='category',
        ),
        migrations.AddField(
            model_name='wheel',
            name='size',
            field=models.ManyToManyField(to='wheel.size'),
        ),
    ]
