# Generated by Django 5.0.2 on 2024-03-10 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0009_wheel_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='month_3_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='month_6_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='month_9_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='wheel',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='wheel.wheel'),
        ),
    ]
