# Generated by Django 5.0.2 on 2024-02-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0009_remove_wheel_category_wheel_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wheel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='wheel',
            name='size',
        ),
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wheel',
            name='category',
            field=models.ManyToManyField(to='wheel.category'),
        ),
    ]
