# Generated by Django 5.0.2 on 2024-03-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0010_alter_detail_month_3_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='size',
            field=models.IntegerField(choices=[(12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')]),
        ),
        migrations.AlterField(
            model_name='wheel',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
