# Generated by Django 5.0.2 on 2024-02-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0011_remove_category_price_remove_category_sizes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheel',
            name='details',
            field=models.ManyToManyField(to='wheel.size'),
        ),
    ]
