# Generated by Django 5.0.2 on 2024-02-22 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0012_wheel_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wheel',
            name='details',
        ),
        migrations.RemoveField(
            model_name='wheel',
            name='category',
        ),
        migrations.AddField(
            model_name='wheel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wheel.category'),
            preserve_default=False,
        ),
    ]
